### ISSUE TITLE
Error: Cannot update 'data.foobar' and 'data.foobar' at the same time

### ISSUE THREAD

**Issue by psixdev** [ExceedeMedia/telegraf-session-mongo#2]
Hi. Simple example of code which causes the problem:
```
bot.on('message', (ctx) => {
	delete ctx.session.counter;
	ctx.session.counter = 0;
});
```
It's just an example, no matter the code is useless.

What's going on in the library:
> delete property counter
```
delete $set[property]; // delete $unset.counter (?!)
$unset[`data.${property}`] = ''; // set $unset['data.counter']
```
> set property counter
```
$set[`data.${property}`] = value; // set $set['data.counter']
delete $unset[property]; // delete $unset.counter (?! field does not exist, existing field - 'data.counter')
```
> saveSession

`data.__changeset` in `this.collection.updateOne` is
```
{ '$set': { 'data.counter': 0, expireAt: 2018-12-05T06:44:08.000Z },
  '$unset': { 'data.counter': '' } }
```
I do not understand why some fields are added, but others (nonexistent) are deleted. After `saveSession` I get an error `MongoError: Cannot update 'data.counter' and 'data.counter' at the same time`. Because of this problem, the scene-based control flow of the telegraph does not work, for example.

**Comment by FowiFlowi** [comment]
#3 Fix
